build:
    environment:
        php: 7.2
    #dependencies:
    #    before:
    #        - sudo apt-get install -y php-phpdbg
    nodes:
        coverage:
            tests:
                override:
                    #- command: phpdbg -qrr ./vendor/bin/phpspec run
                    - command: ./vendor/bin/phpspec run
                      coverage:
                          file: build/clover.xml
                          format: clover
