build:
    environment:
        php: 7.2
    nodes:
        coverage:
            tests:
                override:
                    - command: phpdbg -qrr vendor/bin/phpspec run
                      coverage:
                          file: build/clover.xml
                          format: clover
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - phpdbg -qrr vendor/bin/phpspec run

