build:
    nodes:
        coverage:
            tests:
                dependencies:
                    before:
                        - sudo apt-get install -y php-phpdbg
                override:
                    - command: make test-coverage
                      coverage:
                          file: build/clover.xml
                          format: clover
