build:
    environment:
        php: 7.2
    dependencies:
        before:
            - sudo apt-get install -y php-phpdbg
    nodes:
        coverage:
            tests:
                override:
                    - command: make test-coverage
                      coverage:
                          file: build/clover.xml
                          format: clover
