build:
    nodes:
        coverage:
            dependencies:
                before:
                    - sudo apt-get install -y php-phpdbg
            tests:
                override:
                    - command: make test-coverage
                      coverage:
                          file: build/clover.xml
                          format: clover
