build:
    environment:
        php: 7.2
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - phpdbg -qrr vendor/bin/phpspec run
                    -
                        command: phpcs-run
                        use_website_config: true
        coverage:
            tests:
                override:
                    - command: phpdbg -qrr vendor/bin/phpspec run
                      coverage:
                          file: build/clover.xml
                          format: clover

#build:
#    nodes:
#        analysis:
#            project_setup:
#                override:
#                    - 'true'
#            tests:
#                override:
#                    - php-scrutinizer-run
#                    -
#                        command: phpcs-run
#                        use_website_config: true
#        tests: true
filter:
    excluded_paths:
        - 'spec/*'
checks:
    php: true

coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
            other:
                after_type_cast: false