services:
  pact.matcher:
    class: PhpPact\Consumer\Matcher\Matcher

  behat.matcher:
    class: SmartGamma\Behat\PactExtension\Infrastructure\BehatMatcher
    arguments:
      - "@pact.matcher"

  pact.mock_server.factory:
    class: SmartGamma\Behat\PactExtension\Infrastructure\MockServerFactory

  pact.infrastructure:
    class: SmartGamma\Behat\PactExtension\Infrastructure\Pact
    arguments:
      - '@pact.mock_server.factory'
      - '%pact.common.config%'
      - '%pact.providers.config%'

  pact.compositor:
    class: SmartGamma\Behat\PactExtension\Infrastructure\InteractionCompositor
    arguments:
      - "@behat.matcher"

  pact.context.initializer:
    class: SmartGamma\Behat\PactExtension\Context\Initializer\PactInitializer
    arguments:
      - "@pact.infrastructure"
      - "@pact.compositor"
    tags: [{ name: context.initializer }]
